services:
    traefik:
        image: traefik:v3
        container_name: traefik

        command:
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false

            # HTTP and HTTPS
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443

            # dashboard (local only)
            - --api.insecure=${TRAEFIK_DASHBOARD}
            - --api.dashboard=${TRAEFIK_DASHBOARD}

            # logging
            - --log.level=INFO
            - --accesslog=true
        
        ports:
            - "80:80"

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

        networks:
            - backend

    cyllenian:
        build: .
        container_name: cyllenian
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase-service-account.json
            - DOMAIN=${DOMAIN}
            - LOGLEVEL=${LOGLEVEL}
        volumes:
            - ./firebase-key.json:/run/secrets/firebase-service-account.json:ro
        depends_on:
            - redis
        networks:
            - backend

        # Traefik Labels
        labels:
            - "traefik.enable=true"

            # web to secure if LE_RESOLVER exists
            - "traefik.http.routers.cyllenian.entrypoints=${ENTRYPOINT}"
            - "traefik.http.routers.cyllenian.rule=Host(`${DOMAIN}`)"

            - "traefik.http.services.cyllenian.loadbalancer.server.port=8000"

    ## DB service, linked up to its data volume for persistent storage, and the docker network
    redis:
        image: redis:8.6-alpine
        container_name: redis
        volumes:
            - redis_data:/data
        networks:
            - backend

## DB data storage
volumes:
    redis_data:

## Network for inter-service communication
networks:
    backend: